### ISSUE TITLE
data-toggle

### ISSUE THREAD

**Issue by matthewp** [matthewp/corset#142]
Similar to `attr-toggle`, removes the attribute when the value is false.

```css
#app {
  data-value: theme dark;
  data-toggle: theme true;
}

#app:not(.dark-mode) {
  data-toggle: theme false;
}
```
