### ISSUE TITLE
Identifiers vs. strings

### ISSUE THREAD

**Issue by matthewp** [matthewp/corset#52]
Corset treats identifiers and strings as interchangeable. The only difference is what characters are allowed; identifiers only allow `[a-zA-Z]` (note this is probably not to CSS spec and should be fixed).

The use case here is aesthetics and the belief that there wouldn't be builtin identifiers in Corset.

```css
button {
  event: click var(--increment);
}
```

vs.

```css
button {
  event: "click" var(--increment);
}
```

---

However, @propjockey provided a reason for why we might want builtin identifiers. This would be nice:

```css
.profile:not(.editing) {
  text: initial;
}
```

I think there's a choice here of one of these:

1. Force using strings where identifiers are used now.
    - Maybe this would be more intuitive anyways?
2. Have reserved words like `initial` but otherwise allow identifiers as strings.
    - Hard to predict ahead of time what we need to reserve.
3. Keep identifiers as strings and use functions for things like initial. `initial()`.
    - Might be unexpected coming from CSS.
4. Allow identifiers as strings only in certain properties. For example could we allow them as the event name, without allowing them generally?
